---
- hosts: docker.aghassi.home
  become: true

  vars:
    new_path: "/usr/bin"
  
  vars_prompt:
    - name: git_user
      prompt: Git Username
      private: no
    
    - name: git_password
      prompt: Git Password
      private: yes
  
  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - cifs-utils
          - keyutils
        state: latest
        update_cache: true
      
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian bullseye stable
        state: present

    - name: Update apt and install Docker packages
      apt:
        pkg:
          - uidmap
          - dbus-user-session
          - fuse-overlayfs
          - slirp4netns
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          #- docker-ce-rootless-extras
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker
    
    - name: Install pexpect
      pip:
        name: pexpect
    
    - name: Create docker user
      user:
        name: docker
        group: docker
    
    #- name: Run docker rootless setup script
    #  become: true
    #  become_user: docker
    #  command: sh /usr/bin/dockerd-rootless-setuptool.sh install

    - name: Update PATH environment variable
      lineinfile:
        path: /etc/environment
        state: present
        regexp: '^(PATH=\")({{ new_path }}:)?((?(2).*?(?!(?:.\"))|.*?(?!(?:{{ new_path }}))))(:{{ new_path }})?((?(4).*|\"))'
        line: '\1\3:{{ new_path }}\5'
        backrefs: yes

    # this is for rootless docker, breaks rootful
    #- name: Add DOCKER_HOST environment variable
    #  lineinfile:
    #    path: /etc/environment
    #    state: present
    #    line: DOCKER_HOST=unix:///run/user/1000/docker.sock
    
    - name: Start and enable dockerd
      service:
        name: docker
        state: started
        enabled: true

    - name: Create repository directory
      file:
        path: /repositories
        state: directory
        owner: docker
        group: docker
    
    - name: Add raaghassi to docker group
      user:
        name: raaghassi
        groups: docker
        append: yes
    
    - name: Create aghassi-file/aghassi_media mount point
      file:
        path: /mnt/aghassi-file/aghassi_media
        state: directory
        mode: '0777'

    - name: Create configs mount point
      file:
        path: /mnt/aghassi-file/aghassi_svcs
        state: directory
        mode: '0777'      

    - name: Mount aghassi-file/aghassi_media
      ansible.posix.mount:
        src: "//aghassi-file.aghassi.home/aghassi_media"
        path: "/mnt/aghassi-file/aghassi_media"
        opts: "rw,vers=3,dom=aghassi,username=media,password=media1683,nobrl"
        fstype: cifs
        state: mounted
    
    - name: Mount aghassi-file/aghassi_svcs
      ansible.posix.mount:
        src: "//aghassi-file.aghassi.home/aghassi_svcs"
        path: "/mnt/aghassi-file/aghassi_svcs"
        opts: "rw,vers=3,dom=aghassi,username=media,password=media1683,nobrl"
        fstype: cifs
        state: mounted
    
    - name: Clone the dockerfiles git repo from Gitea
      expect:
        chdir: /repositories
        command: git clone http://git.aghassi.home/raaghassi/aghassi-home-dockerfiles.git
        responses:
          Username: "{{ git_user }}"
          Password: "{{ git_password }}"
        #no_log: true

    - name: Clone configs repo from Gitea
      expect:
        chdir: /repositories
        command: git clone http://git.aghassi.home/raaghassi/aghassi-home-configs.git
        responses:
          username: "{{ git_user }}"
          password: "{{ git_password }}"
